[package]
name = "aarambh-ai-nn"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = [
    "aarambh-ai-core/cuda",
    "aarambh-ai-kernel/cuda",
    "aarambh-ai-quant/cuda",
    "candle-core/cuda",
    "candle-nn/cuda",
]

[dependencies]
aarambh-ai-core = { path = "../aarambh-ai-core" }
aarambh-ai-kernel = { path = "../aarambh-ai-kernel" }
aarambh-ai-quant = { path = "../aarambh-ai-quant" }
candle-core      = { workspace = true }
candle-nn        = { workspace = true }

[dev-dependencies]
aarambh-ai-core = { path = "../aarambh-ai-core" }
candle-core      = { workspace = true }
candle-nn        = { workspace = true }
