[package]
name = "aarambh-ai-core"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = ["candle-core/cuda"]

[dependencies]
candle-core = { workspace = true }
thiserror   = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
