[package]
name = "aarambh-ai-agent"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = ["aarambh-ai-inference/cuda"]

[dependencies]
aarambh-ai-core      = { path = "../aarambh-ai-core" }
aarambh-ai-inference = { path = "../aarambh-ai-inference" }
serde                = { workspace = true }
serde_json           = { workspace = true }
thiserror            = { workspace = true }
