[package]
name = "aarambh-ai-tokenizer"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
aarambh-ai-core = { path = "../aarambh-ai-core" }
tokenizers      = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
