[package]
name = "aarambh-studio-model"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = [
    "aarambh-studio-core/cuda",
    "aarambh-studio-nn/cuda",
    "aarambh-studio-quant/cuda",
    "candle-core/cuda",
    "candle-nn/cuda",
]

[dependencies]
aarambh-studio-core = { path = "../aarambh-studio-core" }
aarambh-studio-nn   = { path = "../aarambh-studio-nn" }
aarambh-studio-quant = { path = "../aarambh-studio-quant" }
candle-core     = { workspace = true }
candle-nn       = { workspace = true }
