[package]
name = "aarambh-ai-quant"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true

[features]
default = []
cuda = [
    "aarambh-ai-core/cuda",
    "candle-core/cuda",
    "candle-nn/cuda",
]

[dependencies]
aarambh-ai-core      = { path = "../aarambh-ai-core" }
candle-core          = { workspace = true }
candle-nn            = { workspace = true }
serde                = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "qat_bench"
harness = false
